### ISSUE TITLE
Service naming/config change

### ISSUE THREAD

**Issue by TomFrost** [TechnologyAdvice/DevLab#2]
The example shows

``` yaml
services:
  - mongodb:mongo
```

as a way to provide a name for the chosen service. Two issues there:
- The syntax used is the standard syntax for choosing a tag, so it's unintuitive
- We're not providing a way to choose tag

So I suggest we allow this...

``` yaml
services:
  - mongodb
```

or this

``` yaml
services:
  - mongodb:3.0
```

As well as this:

``` yaml
services:
  - mongodb:3.0:
      name: mymongo  # Defaults to projectname_mongodb_3.0 if not specified
      repo: quay.io/yadda  # Defaults to standard docker hub
      auth: blahblah  # defaults to public access
      env:
        DB_ROOT_PASSWORD: testing123 # many services require their own envs to set things like this up, defaults to no additional envs
      exec: |
        # a script to run after the box stands up. Allows us to bootstrap schemas into a DB or something.
        # This is a HUGE feature that not even Wercker supports, but we could, and it would work in dev and test.
      persist: false # Default true. Specifies whether or not the box is torn down and re-created with each run.
```
