### ISSUE TITLE
Link services via path to (external) devlab project

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#28]
Ability to specify a service via path + task, i.e.:

```
services:
    - restapi:
        path: /projects/restapi
        task: run
```

Additionally, path should support environment variables to allow dynamic paths based on user's local config, for example: `path: $RESTAPI_PATH`
