### ISSUE TITLE
Add `exec` to service config

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#3]
Add ability to specify an `exec` to run when the (to be) linked service is started:

```yaml
services:
  - mongo:3.0:
      name: mongodb
      env:
        - DB_ROOT_PASSWORD=foo
      expose:
        - 27017:27017
      persist: false
      exec: |
        some command
```
