### ISSUE TITLE
Disable services (opt-out) by task

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#34]
Allow task definitions to explicitly define unneeded services:

```yaml
services:
  - mongodb:
    from: mongo:3.0
tasks:
  lint:
    disable:
      - mongodb
    cmd: npm run lint
```
