### ISSUE TITLE
Chaining lab commands sometimes results in `&& &&`

### ISSUE THREAD

**Issue by stephen-ta** [TechnologyAdvice/DevLab#47]
Seems with happen with `tasks` that are multiple lines called back to back in the chain

**Comment by Fluidbyte** [comment]
Replicated via the following:

devlab.yml

```yaml
tasks:
  clean: |
    rm -rf node_modules
    rm -rf coverage
  install: yarn
```

command:

```
> devlab clean install
```

fails when following command tries to run:

```
> rm -rf node_modules && rm -rf coverage &&  && yarn
```
