### ISSUE TITLE
Add Multi-Task Run

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#5]
Add the ability to run multiple tasks in one command.

Proposed approach:

```
tasks:
    install: npm install
    lint: npm run lint
    test: npm test
    all: $install $lint $test
```

The above `all` would start the container and any linked services + setup, then run `install`, `lint`, and `test`
