### ISSUE TITLE
Add ability to override default `stop` grace period

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#58]
As some (service) containers seem to hang, or ignore the `SIGTERM` sent to `PID 1` by `docker stop` completely, add ability to specify grace period for services:

```yaml
  - container:
      from: some/image:tag
      stopTimeSecs: <n>
```

`n` would be an integer representing number of seconds before forcing shutdown with `SIGKILL`. If not specified would default to Docker's default of `10`.
