### ISSUE TITLE
Custom Order in Starting or avoiding paralelling

### ISSUE THREAD

**Issue by beeva-manueldepaz** [TechnologyAdvice/DevLab#66]
Hi,

I've a question due to the new version v3 that you can gently help me.
We're trying to start a custom container that have some dependencies with other services (databases) in same *devlab.yml* . In the past, we were using "link" tag and the order of the containers executions was sequentially, so there was no dependencies problem.

Is there something that changed in the new version that I have into account in order to manage this issue?

A little sample could be:
````
from: mhart/alpine-node:latest
services:
  - elasticsearch:
      from: elasticsearch:2.3.0
      persist: false
      expose:
  - mycontainer:
      from: myservice:latest
      persist: false
      link:
        - elasticsearch
      expose:
        - 9000:9000
expose:
  - 7000:7000
  - 5858:5858
env:
  - LOCAL_HOME=${HOME}
forward: true
before: echo "Waiting for services startup" && sleep 10
tasks:
  env: env
  install: npm install
  start: npm start
````

Many thanks in advance,
Manuel
